#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-home_assistant_frontend
Version  : 20220202.0
Release  : 281
URL      : https://files.pythonhosted.org/packages/15/5a/b2710790530e7a63d3db3e2d062cd9cd87a6cc7ee11dedba3ff2cb73ec45/home-assistant-frontend-20220202.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/15/5a/b2710790530e7a63d3db3e2d062cd9cd87a6cc7ee11dedba3ff2cb73ec45/home-assistant-frontend-20220202.0.tar.gz
Summary  : The Home Assistant frontend
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: pypi-home_assistant_frontend-license = %{version}-%{release}
Requires: pypi-home_assistant_frontend-python = %{version}-%{release}
Requires: pypi-home_assistant_frontend-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
# Home Assistant Frontend
This is the repository for the official [Home Assistant](https://home-assistant.io) frontend.

%package license
Summary: license components for the pypi-home_assistant_frontend package.
Group: Default

%description license
license components for the pypi-home_assistant_frontend package.


%package python
Summary: python components for the pypi-home_assistant_frontend package.
Group: Default
Requires: pypi-home_assistant_frontend-python3 = %{version}-%{release}

%description python
python components for the pypi-home_assistant_frontend package.


%package python3
Summary: python3 components for the pypi-home_assistant_frontend package.
Group: Default
Requires: python3-core
Provides: pypi(home_assistant_frontend)

%description python3
python3 components for the pypi-home_assistant_frontend package.


%prep
%setup -q -n home-assistant-frontend-20220202.0
cd %{_builddir}/home-assistant-frontend-20220202.0
pushd ..
cp -a home-assistant-frontend-20220202.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656380712
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend
cp %{_builddir}/home-assistant-frontend-20220202.0/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4a606a34022a7ef2eab88e43148dd48547d3c017
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/01620c6b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/02452dec.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/6bde043283d03e8b99c063d2ba126e25d4d8266f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/03554b2b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/042a75a6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/04b256de.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/07fc080e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/0826d03c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/09595d3a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/0ca87d17.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/107a760c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/111bde1d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/1518c991.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/1a690620.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c66394b1e4d56b9ff5804fc9ada793a44874c1d2
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/1b08a3ad.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/1d2d2111.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/e574e3c0f96a21b6afa716c305ec63c8b35db62a
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/1e819785.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/222b1ceb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/2244d7f7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/227fba30.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/25118ba7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/274f92da.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/2967afa3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/2c6647e9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/2df2591a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/312ebce9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/3298ffcf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/34e8e4fc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/34fd0e1f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/3959d437.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/39f194bb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a8dc9f8fec60a86b68053048c025a56e6b7f8121
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/3c18ca12.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/3c4dd7fe.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/3cb90e6b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/2b4c3c5b9144751f497ce2985ea8d72881838f7a
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/3e358557.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/40b1ed3e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/413fda30.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/421422fe.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/440f609d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c66394b1e4d56b9ff5804fc9ada793a44874c1d2
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/4455a82f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/45fc28d3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/68c9a4a0ed7a38283512b48691ae8e138a0eef2d
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/46fe4dbc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/4d28c451.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/4d33e831.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/4d7cd98c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/51cb422b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c7c71dd8cf0383cb862cf098c82112c6bbfe00c9
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/57688e0b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/5770eebc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/57720e60.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/5d305500.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/5eca512d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/5eda70f4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/60f35047.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/63881635.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/66409ee6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/67ce630e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c9e471b5af473fd9bc91b567c6b400d4ed443fc7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/69efb8d8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c9e471b5af473fd9bc91b567c6b400d4ed443fc7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/6afed2e4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/6cbb323e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/6fc2a384.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/702ffe54.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/708e8f79.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/70fc277e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0ea60763f8a4f889dbe6cce3c82511958700a600
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/7120fcff.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/7169911b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/75e0f4af.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/786070c5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4fe3230400911d4d8dc2891094c03f2c452fba6e
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/7a86d30a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c66394b1e4d56b9ff5804fc9ada793a44874c1d2
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/7a8a6971.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/7b72f88a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/7fdbbf0f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/809f1604.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/8b28c603.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/8d21593c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/8d91c6b0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/8d9b15fd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/3a649ad7ec864269cdd4583212f43eef748af042
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/907f0f55.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/91a8ec95.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/925776f5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/9fdb1ff9635426575a6738844d37ca296a7df621
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/95160970.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/99cae8b9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/9b0148e5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/9b86318f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/9b89b643.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/9d687a80.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/a15e1247.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/a1845799.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/a22751ef.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/a23c8f5c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/a3f5ba4d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/a7357f5d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/2b4c3c5b9144751f497ce2985ea8d72881838f7a
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/a7506524.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/ad1062d7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/ae10e573.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c66394b1e4d56b9ff5804fc9ada793a44874c1d2
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/authorize.822a6186.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c52bbed517be898a5cd28c5a45a896ee3bd5d8b1
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/b10c4ce0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/b8081721.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/bd786574.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/befabf25.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/bf05ba69.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/7ca86776b148e24ec023907f66030cc21c4e559d
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/bfcf99af.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/c22ed41f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/c338bac8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/c39d1e5c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/c506feae.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/c58aba2a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/c9a53031.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/c9dc9186.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/e85c7adbabceadcefbb2c4bd6d950e1287e90191
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/cd48c376.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/e5a5f9f10965f8ef5f09e477f19ed8e580939e3f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/d1109977.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/d2c3b224.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/68c9a4a0ed7a38283512b48691ae8e138a0eef2d
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/d9a0cad4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/de5f6ecf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/e421152f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/e4813a2b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/e57a257e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/e69ae738.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/e8c69b74.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/e8f7fefa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/ea787b1f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/eaed7a5b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/ed1b7661.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/7f822fe9341af8f82ad1b0c69aba957822a377cf
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/ed429765.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c9e471b5af473fd9bc91b567c6b400d4ed443fc7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/f4fa770a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/f94f9c52.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0b751618d82d48636b86d46f4290cd4d97e7f1f9
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/fcb5fc73.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/fdd6daab.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/ffeb5a38.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_es5/onboarding.7938f233.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d5e80ede95bb4858eef3759e9fe9b4fbcaf7f351
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/014b6f4e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/89f2ae5077fb5ade2295231f047cf8f6b1d5f92b
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/01df4ee6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/08b97b7a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/0b77a1e0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/9fdb1ff9635426575a6738844d37ca296a7df621
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/0cc6032b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/0d5430cd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/2b4c3c5b9144751f497ce2985ea8d72881838f7a
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/0d6d9a29.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/0ed8bc7e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/0f5bd5ca.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/10142620.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/1157d994.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/11ce46c9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/1608b185.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/1673441b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/16c41349.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/1a5e7444.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0eab032fb05337d310c726a4cad37c72cbcf0798
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/1a793565.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/1ae55809.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/1bf7449b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/2b4c3c5b9144751f497ce2985ea8d72881838f7a
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/1c6fe301.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/1f3f8c5c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/1f932cef.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/21f9ad7a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/24d3d06c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/27bc699e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/28e51b23.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0ea60763f8a4f889dbe6cce3c82511958700a600
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/2b6393af.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c65471f722708cded989e0c8b1ed417c24461c5e
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/2bbd784c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/2f85899a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/328b73d3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/35564c13.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/362bcc69.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/38188e47.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/38883654.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/9df6942b5a07135e71dea56a6a258ac1159ed21a
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/39cd1f0e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/39e1953e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/3b2bfd0b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/3c984427.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/3cba5db8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/3d33ed90.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/3f59d39b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/402d5a05.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/44951cc0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/45d65f61.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/475d8cba.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/4a299c85.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/9bfa2369fc2eed95cbe8189a2952b83c722bbefb
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/4a4d3248.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/9bfa2369fc2eed95cbe8189a2952b83c722bbefb
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/4bfff2c5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/4de70bb0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/525a96b8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c595e321bdfeb39e3e97bd1b0b68386f49e0c01e
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/54e18809.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/5625d7f2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/59273557.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/6bde043283d03e8b99c063d2ba126e25d4d8266f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/5dbbe80d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/606c5e68.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/62b237e0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/63861f92.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/6511d677.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/9bfa2369fc2eed95cbe8189a2952b83c722bbefb
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/652d2860.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/679ae7e2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/6df6f835.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/9bfa2369fc2eed95cbe8189a2952b83c722bbefb
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/759bfe14.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/75f17777.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/3a649ad7ec864269cdd4583212f43eef748af042
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/761d96a4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c7c71dd8cf0383cb862cf098c82112c6bbfe00c9
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/76f351df.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/7715bf88.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/77186c92.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/7937b869.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/79481528.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/848b5fcb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/89767b16.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/8c303377.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/8f570823.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/93b7b7b6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/9463dd72.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/94f87e39.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0eab032fb05337d310c726a4cad37c72cbcf0798
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/95608cdd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/68c9a4a0ed7a38283512b48691ae8e138a0eef2d
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/97637d5e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/97a208ac.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/9954b0ad.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/99a597ba.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/9ae3ebe4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/9b241b1e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d3d1cbbad751ce5466fabaa5db82ff4e2b62f9f3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/9d0f5019.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/a08c96b7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/a1099737.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/a1ec982b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/a2165bc2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/a31dbaa5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/a550c400.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/a6596fb0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/7f822fe9341af8f82ad1b0c69aba957822a377cf
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/a6e0859e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/a713a0b9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/ae8a84b3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/af94b0df.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/authorize.52419d11.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4f3491f3f5ec852d59f301e367997af530e71f25
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/b1d378dd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/b41be8f2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/b63037f6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/026143893f709c4edbdf27d0eef7e8160ebfd059
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/b6a4e485.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/bbb99704.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/bbca7043.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/bc6487de.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/be3db3b8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/bfa552b6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/c0999775.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/c17f4e95.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/c335fc34.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/c74510a7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/c7a6f2d9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/c803ea62.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a8dc9f8fec60a86b68053048c025a56e6b7f8121
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/c80c7324.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/c85c200e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/ca9746b2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4fe3230400911d4d8dc2891094c03f2c452fba6e
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/caf06af7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/cf448587.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/cfba4c02.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/d424af7e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/6989900c41e7d834ce246e4de36c40374cbc160c
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/d472da3a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/d4f07e6a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/d50de5d8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/7ca86776b148e24ec023907f66030cc21c4e559d
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/d6f285dd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/d7c2afab.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/d97f4f43.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/d9ad8f35.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0f1ee3f69ca6ab90f050775eae6ce6f1a14bb432
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/dad6e3e8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/db5a77cf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/de19ae9c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/e053c038.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d3d1cbbad751ce5466fabaa5db82ff4e2b62f9f3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/e0f1f304.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/e6d15021.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/e8b24400.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/e8ce1a9c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/e98f2caa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/89f2ae5077fb5ade2295231f047cf8f6b1d5f92b
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/eab9d01e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0b751618d82d48636b86d46f4290cd4d97e7f1f9
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/f178cc17.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/f245a468.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/f48fc38d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/f6d48bfe.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/ee8dd7e66e20217fedd62d9529a842bd9200b446
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/f7df0e52.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0eab032fb05337d310c726a4cad37c72cbcf0798
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/f82b40c0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/fa0d37d5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/fa50af4c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/fb68f320.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/fca64c46.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/fe9cd448.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d3d1cbbad751ce5466fabaa5db82ff4e2b62f9f3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/ff42ff20.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220202.0/hass_frontend/frontend_latest/onboarding.65cda9c6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c780796884df62b955cbb838225a1770ea5937dd
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-home_assistant_frontend/026143893f709c4edbdf27d0eef7e8160ebfd059
/usr/share/package-licenses/pypi-home_assistant_frontend/0b751618d82d48636b86d46f4290cd4d97e7f1f9
/usr/share/package-licenses/pypi-home_assistant_frontend/0ea60763f8a4f889dbe6cce3c82511958700a600
/usr/share/package-licenses/pypi-home_assistant_frontend/0eab032fb05337d310c726a4cad37c72cbcf0798
/usr/share/package-licenses/pypi-home_assistant_frontend/0f1ee3f69ca6ab90f050775eae6ce6f1a14bb432
/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
/usr/share/package-licenses/pypi-home_assistant_frontend/2b4c3c5b9144751f497ce2985ea8d72881838f7a
/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
/usr/share/package-licenses/pypi-home_assistant_frontend/3a649ad7ec864269cdd4583212f43eef748af042
/usr/share/package-licenses/pypi-home_assistant_frontend/4a606a34022a7ef2eab88e43148dd48547d3c017
/usr/share/package-licenses/pypi-home_assistant_frontend/4f3491f3f5ec852d59f301e367997af530e71f25
/usr/share/package-licenses/pypi-home_assistant_frontend/4fe3230400911d4d8dc2891094c03f2c452fba6e
/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
/usr/share/package-licenses/pypi-home_assistant_frontend/68c9a4a0ed7a38283512b48691ae8e138a0eef2d
/usr/share/package-licenses/pypi-home_assistant_frontend/6989900c41e7d834ce246e4de36c40374cbc160c
/usr/share/package-licenses/pypi-home_assistant_frontend/6bde043283d03e8b99c063d2ba126e25d4d8266f
/usr/share/package-licenses/pypi-home_assistant_frontend/7ca86776b148e24ec023907f66030cc21c4e559d
/usr/share/package-licenses/pypi-home_assistant_frontend/7f822fe9341af8f82ad1b0c69aba957822a377cf
/usr/share/package-licenses/pypi-home_assistant_frontend/89f2ae5077fb5ade2295231f047cf8f6b1d5f92b
/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
/usr/share/package-licenses/pypi-home_assistant_frontend/9bfa2369fc2eed95cbe8189a2952b83c722bbefb
/usr/share/package-licenses/pypi-home_assistant_frontend/9df6942b5a07135e71dea56a6a258ac1159ed21a
/usr/share/package-licenses/pypi-home_assistant_frontend/9fdb1ff9635426575a6738844d37ca296a7df621
/usr/share/package-licenses/pypi-home_assistant_frontend/a8dc9f8fec60a86b68053048c025a56e6b7f8121
/usr/share/package-licenses/pypi-home_assistant_frontend/c52bbed517be898a5cd28c5a45a896ee3bd5d8b1
/usr/share/package-licenses/pypi-home_assistant_frontend/c595e321bdfeb39e3e97bd1b0b68386f49e0c01e
/usr/share/package-licenses/pypi-home_assistant_frontend/c65471f722708cded989e0c8b1ed417c24461c5e
/usr/share/package-licenses/pypi-home_assistant_frontend/c66394b1e4d56b9ff5804fc9ada793a44874c1d2
/usr/share/package-licenses/pypi-home_assistant_frontend/c780796884df62b955cbb838225a1770ea5937dd
/usr/share/package-licenses/pypi-home_assistant_frontend/c7c71dd8cf0383cb862cf098c82112c6bbfe00c9
/usr/share/package-licenses/pypi-home_assistant_frontend/c9e471b5af473fd9bc91b567c6b400d4ed443fc7
/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
/usr/share/package-licenses/pypi-home_assistant_frontend/d3d1cbbad751ce5466fabaa5db82ff4e2b62f9f3
/usr/share/package-licenses/pypi-home_assistant_frontend/d5e80ede95bb4858eef3759e9fe9b4fbcaf7f351
/usr/share/package-licenses/pypi-home_assistant_frontend/e574e3c0f96a21b6afa716c305ec63c8b35db62a
/usr/share/package-licenses/pypi-home_assistant_frontend/e5a5f9f10965f8ef5f09e477f19ed8e580939e3f
/usr/share/package-licenses/pypi-home_assistant_frontend/e85c7adbabceadcefbb2c4bd6d950e1287e90191
/usr/share/package-licenses/pypi-home_assistant_frontend/ee8dd7e66e20217fedd62d9529a842bd9200b446
/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
/usr/share/package-licenses/pypi-home_assistant_frontend/fb3724a403cfac8a891cbd6be583aaa458459643

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
