#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-home_assistant_frontend
Version  : 20220126.0
Release  : 276
URL      : https://files.pythonhosted.org/packages/e0/f6/9d9a98f428e3d3a6374beff5cc3dde4a387ba8c865312f7d5ddf624fb8df/home-assistant-frontend-20220126.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e0/f6/9d9a98f428e3d3a6374beff5cc3dde4a387ba8c865312f7d5ddf624fb8df/home-assistant-frontend-20220126.0.tar.gz
Summary  : The Home Assistant frontend
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: pypi-home_assistant_frontend-license = %{version}-%{release}
Requires: pypi-home_assistant_frontend-python = %{version}-%{release}
Requires: pypi-home_assistant_frontend-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Home Assistant Frontend
This is the repository for the official [Home Assistant](https://home-assistant.io) frontend.

%package license
Summary: license components for the pypi-home_assistant_frontend package.
Group: Default

%description license
license components for the pypi-home_assistant_frontend package.


%package python
Summary: python components for the pypi-home_assistant_frontend package.
Group: Default
Requires: pypi-home_assistant_frontend-python3 = %{version}-%{release}

%description python
python components for the pypi-home_assistant_frontend package.


%package python3
Summary: python3 components for the pypi-home_assistant_frontend package.
Group: Default
Requires: python3-core
Provides: pypi(home_assistant_frontend)

%description python3
python3 components for the pypi-home_assistant_frontend package.


%prep
%setup -q -n home-assistant-frontend-20220126.0
cd %{_builddir}/home-assistant-frontend-20220126.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643243327
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend
cp %{_builddir}/home-assistant-frontend-20220126.0/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4a606a34022a7ef2eab88e43148dd48547d3c017
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/001fd54b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f357a882b4c98ae48dc95c5ae65016cd63e93365
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/01620c6b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/024feb6a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4fe3230400911d4d8dc2891094c03f2c452fba6e
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/04b256de.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/05343032.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/068302c6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/06e41be4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/0757d605.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/07fc080e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/08f21f28.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/09917ab0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/0a500f99.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/ed241054656f3b1ac94c9156de24b195a052aa31
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/0ca87d17.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/0d47c8f0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/0d661792.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/0e271c1b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/114b6c35.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/eb208c601bcc66bf0a9f23d7fc873698f9799ad4
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/146b4806.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/2b4c3c5b9144751f497ce2985ea8d72881838f7a
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/1518c991.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/1637ffd7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/19f9d06c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/1b08a3ad.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/1c08c71c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/1d2d2111.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/e574e3c0f96a21b6afa716c305ec63c8b35db62a
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/1fc408a0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/20afacf5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/ed241054656f3b1ac94c9156de24b195a052aa31
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/2467d51c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/25118ba7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/28acebd2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/2accb695.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/2c9dc15a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/2cb23324.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/2f7caa6d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/312ebce9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/31c10310.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/31de8d59.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/34e8e4fc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/353819a8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/35f6da11.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/3c4dd7fe.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/3e00a444.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/3e358557.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/3fd38725.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/112e87654b9adbdccbb20863a114d9ad3d99c8cc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/4000b798.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/40c348a9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/411f0a84.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/421422fe.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/43257ebb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/436d7a63.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/45fc28d3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/68c9a4a0ed7a38283512b48691ae8e138a0eef2d
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/4807b7aa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c9e471b5af473fd9bc91b567c6b400d4ed443fc7
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/4989a3fa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/4d28c451.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/4d33e831.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/4fa08388.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/ed241054656f3b1ac94c9156de24b195a052aa31
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/4fca90b6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/ed241054656f3b1ac94c9156de24b195a052aa31
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/5784f083.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/586613ec.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/71968af288c4c7d4ed0c4565381830db24dc4dff
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/58ee8494.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/5d305500.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/5fd9e6b1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/5ffd0f16.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/62a54b84.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/62f32c12.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/646dbfba.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/66409ee6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/668e4dd8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/688beb3b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/835ee1b049a8047518b8a9c5c4783563e575e23e
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/6afed2e4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/6d5e00fc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/29d1c09ecc9948b460f27a322692ec33d9a94cfd
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/6d83a5b1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/ed241054656f3b1ac94c9156de24b195a052aa31
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/6fc5658b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/708e8f79.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/70b99862.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/7423f1e3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0b751618d82d48636b86d46f4290cd4d97e7f1f9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/749e442c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a8dc9f8fec60a86b68053048c025a56e6b7f8121
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/74df79ad.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0ea60763f8a4f889dbe6cce3c82511958700a600
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/75276f74.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/75dbc527.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/75e0f4af.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/78a40f31.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/7a8a6971.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/7d9ded6c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/eb208c601bcc66bf0a9f23d7fc873698f9799ad4
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/7eaaa2b1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/7f0351eb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/7fdbbf0f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/80bdf48c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/ed241054656f3b1ac94c9156de24b195a052aa31
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/80e2fe7a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/7589786cde21e316a987007e9d41d72bc6636a6f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/814ee0fa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/e85c7adbabceadcefbb2c4bd6d950e1287e90191
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/829f997f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/9188b8b3154cc352eab6ef20bce25a641a2d4544
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/835289cc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/83deacba.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/8594b3f2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/89e05341.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/8b945dbb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/8c46a15e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/8d1dd654.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/8d21593c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/8d91c6b0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/8d9b15fd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/3a649ad7ec864269cdd4583212f43eef748af042
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/8dbd77d9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/8fc3f949.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/907f0f55.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/908ced3c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/9177d4cd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/669c818f065d6cfbc672b3b9e1943759c7531db2
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/91a8ec95.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/92a52ab7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f357a882b4c98ae48dc95c5ae65016cd63e93365
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/94f2eb98.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/96e00ff9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/99cae8b9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/9a881972.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f357a882b4c98ae48dc95c5ae65016cd63e93365
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/9d687a80.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/a1845799.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/a19e50ca.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/a2b936dc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/ed241054656f3b1ac94c9156de24b195a052aa31
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/a2fac600.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/80a02612c79a42edc043ba543351c469a3980988
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/a38dcc56.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/e5a5f9f10965f8ef5f09e477f19ed8e580939e3f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/a3f5ba4d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/a6cc49a5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/a7506524.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/a956563e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/aa1b8f24.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/2b4c3c5b9144751f497ce2985ea8d72881838f7a
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/aa54a8a1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/aaf99fd3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c9e471b5af473fd9bc91b567c6b400d4ed443fc7
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/authorize.af28a736.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c52bbed517be898a5cd28c5a45a896ee3bd5d8b1
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/b0f26fa2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c7c71dd8cf0383cb862cf098c82112c6bbfe00c9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/b8081721.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/ba094f18.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/80a02612c79a42edc043ba543351c469a3980988
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/bc702651.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/bc716de9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/bde40d51.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/bfb1f247.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/bfcf99af.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/c0cb4fa6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/c39d1e5c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/c3e00ffa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/c58aba2a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/c62892e5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/cb521613.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/cc09b110.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/ed241054656f3b1ac94c9156de24b195a052aa31
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/cce37586.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/cd8f88c5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/d095ab82.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/d1109977.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/d21c24d5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/d2c3b224.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/68c9a4a0ed7a38283512b48691ae8e138a0eef2d
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/d57edbf1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/d663b2f2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/d7f7d1ef.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/d8caec44.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/d9ba2282.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/dce2c025.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/de5f6ecf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/de9b5195.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/e3b4907c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/b4f46072474f11d4a34f150fc3d73435b4349e60
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/e57a257e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/e64aebaa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/e656bace.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/71968af288c4c7d4ed0c4565381830db24dc4dff
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/ed1b7661.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/7f822fe9341af8f82ad1b0c69aba957822a377cf
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/ee602833.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c9e471b5af473fd9bc91b567c6b400d4ed443fc7
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/f2a43f68.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/f359a0c6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/f5d1aa2b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/f8cdf367.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c66394b1e4d56b9ff5804fc9ada793a44874c1d2
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/fb3e7424.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/fe24d7ab.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_es5/onboarding.4224c9fa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d5e80ede95bb4858eef3759e9fe9b4fbcaf7f351
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/004130b4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0ea60763f8a4f889dbe6cce3c82511958700a600
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/038e1672.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/b022ae1a00b41126bc4b72aa14c4b217409cbad2
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/03ffe5ff.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/05a1bed8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/026143893f709c4edbdf27d0eef7e8160ebfd059
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/07560467.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/0901a0c9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/80a02612c79a42edc043ba543351c469a3980988
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/09d3d4ff.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/0af1776d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/0d6d9a29.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/0f4a95c6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/10fdf678.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/1157d994.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/117980e6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/12168899.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/14b25553.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/153e7ad7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/33fde0a30924ce613b40a931bff38fd8516d2f56
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/16c41349.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/17ca6d14.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/18bf3da0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/2b4c3c5b9144751f497ce2985ea8d72881838f7a
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/19229475.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/32fe6e1511820b2c1e1bb8cb2c9c05deb6a48428
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/19d39b37.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/9df6942b5a07135e71dea56a6a258ac1159ed21a
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/1c6fe301.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/1ccfd914.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/71968af288c4c7d4ed0c4565381830db24dc4dff
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/1fc0d98a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/213df82c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/21f9ad7a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/260e96d9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/27bc699e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/29055d08.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/2bece890.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/2d4b2e0e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/2f85899a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/2f8db67e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0eab032fb05337d310c726a4cad37c72cbcf0798
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/34c9bbe0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/35564c13.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/3559f598.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/3856d099.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/38769932.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/38b53b2b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/9188b8b3154cc352eab6ef20bce25a641a2d4544
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/396e1643.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/39cd1f0e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/39e1953e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/3c984427.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/3ea14226.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/3f59d39b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/3fe5fcc8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4b9d8edd7a39d4d21c6cf5f6c94c93a64525c1a9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/42973e9d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/45d65f61.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/4650d96d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/4892387f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/2b4c3c5b9144751f497ce2985ea8d72881838f7a
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/498c6400.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/4b8c68ce.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/4bd6faee.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/4bfff2c5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/4d86aee6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/4de70bb0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/5186f031.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4b9d8edd7a39d4d21c6cf5f6c94c93a64525c1a9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/532d08d0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c7c71dd8cf0383cb862cf098c82112c6bbfe00c9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/53439f8c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/026143893f709c4edbdf27d0eef7e8160ebfd059
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/5549c2df.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/59529d24.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/83389be5ca12156e489018273f6f1e9454eea60c
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/59cb0f43.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4b9d8edd7a39d4d21c6cf5f6c94c93a64525c1a9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/5baf2b2e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/5bf0e253.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/5c0d37e4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/5ddb4311.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/606c5e68.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/619a63e6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/61d367c6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/62b237e0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/62de58eb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/33fde0a30924ce613b40a931bff38fd8516d2f56
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/652d2860.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/65526f52.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/835ee1b049a8047518b8a9c5c4783563e575e23e
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/6596d881.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/7589786cde21e316a987007e9d41d72bc6636a6f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/66a42a57.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0b751618d82d48636b86d46f4290cd4d97e7f1f9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/6812a81b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/b4f46072474f11d4a34f150fc3d73435b4349e60
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/6df9a85f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/6f727a0c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/83389be5ca12156e489018273f6f1e9454eea60c
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/7097adc3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/73a495d7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/75f17777.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/3a649ad7ec864269cdd4583212f43eef748af042
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/76f351df.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/7715bf88.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/77c02791.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/77eba30f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/9fdb1ff9635426575a6738844d37ca296a7df621
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/794c7f36.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/7bee268b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/83389be5ca12156e489018273f6f1e9454eea60c
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/7e3cc3bd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/7f2c78a6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/7fad5a22.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/862a8d65.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/872ac332.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/669c818f065d6cfbc672b3b9e1943759c7531db2
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/885f10d3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/738d95c9247bf21af162a126da83b312ee64883f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/8897bd88.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/892c8d63.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/89767b16.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/8c303377.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/8d10815e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a8f6fd9479379bced7de01e3dab9de4defda26e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/8f570823.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/9318798d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/026143893f709c4edbdf27d0eef7e8160ebfd059
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/9463dd72.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/95608cdd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/68c9a4a0ed7a38283512b48691ae8e138a0eef2d
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/97637d5e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/98003ebb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/eb208c601bcc66bf0a9f23d7fc873698f9799ad4
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/9954b0ad.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/99a597ba.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/9b4ab019.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/9d0f5019.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/a1ec982b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/a1fa286f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/a495b85e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/a5580997.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/a6596fb0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/7f822fe9341af8f82ad1b0c69aba957822a377cf
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/a6a1e095.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/a6e0859e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/a70482d5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/a713a0b9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/a80a6b12.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/ac036dec.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4b9d8edd7a39d4d21c6cf5f6c94c93a64525c1a9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/authorize.5a9918da.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/6bda7eb2ddfd8a99d7e8da50fb6f1e96805f3edd
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/b36892e7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/24db3a1828c8695cf5e05649e4a5f007c997927b
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/b3de29f8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a8dc9f8fec60a86b68053048c025a56e6b7f8121
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/b41be8f2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/b7bbb69d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/b942b134.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/33fde0a30924ce613b40a931bff38fd8516d2f56
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/bbb99704.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/bc46ea0a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/be3db3b8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/be5c5ed3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/bfa552b6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/c28a5cee.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/c3768f5e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4b9d8edd7a39d4d21c6cf5f6c94c93a64525c1a9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/c5b4995b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/ca5592df.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/caf06af7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/cb1c0a9c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/cf1936b8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/eb208c601bcc66bf0a9f23d7fc873698f9799ad4
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/d472da3a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/d47828ff.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/d4f07e6a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/d6f285dd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/d790279c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/d7bcbc0b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/045830db3e7b168e1f6651bd10bd47709e0a1e0a
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/d893f822.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/d8d62d7b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/db5a77cf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/dde685e8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/deac67b0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/e0b7f372.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/80a02612c79a42edc043ba543351c469a3980988
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/e1fee014.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/e2934194.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4b9d8edd7a39d4d21c6cf5f6c94c93a64525c1a9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/e5079c63.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4fe3230400911d4d8dc2891094c03f2c452fba6e
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/e575e133.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/e694bb7b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/026143893f709c4edbdf27d0eef7e8160ebfd059
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/e6d15021.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/e742a6e4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/ea391071.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4b9d8edd7a39d4d21c6cf5f6c94c93a64525c1a9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/ea672be0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/ea8b63e0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/ead061bf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/8eaae83a886ac672f4951ec3845ed8ed6800f330
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/f245a468.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/f6d48bfe.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/ee8dd7e66e20217fedd62d9529a842bd9200b446
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/f7e466ce.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/0f1ee3f69ca6ab90f050775eae6ce6f1a14bb432
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/f82b40c0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/fa0d37d5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/fa50af4c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/fa726b61.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/fcf80acb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/4b9d8edd7a39d4d21c6cf5f6c94c93a64525c1a9
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/fdcd0e5f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/8eaae83a886ac672f4951ec3845ed8ed6800f330
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/fdd2cb7f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20220126.0/hass_frontend/frontend_latest/onboarding.4024cfea.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-home_assistant_frontend/c780796884df62b955cbb838225a1770ea5937dd
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-home_assistant_frontend/026143893f709c4edbdf27d0eef7e8160ebfd059
/usr/share/package-licenses/pypi-home_assistant_frontend/045830db3e7b168e1f6651bd10bd47709e0a1e0a
/usr/share/package-licenses/pypi-home_assistant_frontend/0b751618d82d48636b86d46f4290cd4d97e7f1f9
/usr/share/package-licenses/pypi-home_assistant_frontend/0ea60763f8a4f889dbe6cce3c82511958700a600
/usr/share/package-licenses/pypi-home_assistant_frontend/0eab032fb05337d310c726a4cad37c72cbcf0798
/usr/share/package-licenses/pypi-home_assistant_frontend/0f1ee3f69ca6ab90f050775eae6ce6f1a14bb432
/usr/share/package-licenses/pypi-home_assistant_frontend/112e87654b9adbdccbb20863a114d9ad3d99c8cc
/usr/share/package-licenses/pypi-home_assistant_frontend/1f58d528f9edf5c2b5839f7523cf3fb3de5230f7
/usr/share/package-licenses/pypi-home_assistant_frontend/24db3a1828c8695cf5e05649e4a5f007c997927b
/usr/share/package-licenses/pypi-home_assistant_frontend/29d1c09ecc9948b460f27a322692ec33d9a94cfd
/usr/share/package-licenses/pypi-home_assistant_frontend/2b4c3c5b9144751f497ce2985ea8d72881838f7a
/usr/share/package-licenses/pypi-home_assistant_frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
/usr/share/package-licenses/pypi-home_assistant_frontend/32fe6e1511820b2c1e1bb8cb2c9c05deb6a48428
/usr/share/package-licenses/pypi-home_assistant_frontend/33fde0a30924ce613b40a931bff38fd8516d2f56
/usr/share/package-licenses/pypi-home_assistant_frontend/3a649ad7ec864269cdd4583212f43eef748af042
/usr/share/package-licenses/pypi-home_assistant_frontend/4a606a34022a7ef2eab88e43148dd48547d3c017
/usr/share/package-licenses/pypi-home_assistant_frontend/4b9d8edd7a39d4d21c6cf5f6c94c93a64525c1a9
/usr/share/package-licenses/pypi-home_assistant_frontend/4fe3230400911d4d8dc2891094c03f2c452fba6e
/usr/share/package-licenses/pypi-home_assistant_frontend/5c836fda5dcfa800cebbe7bdb119872990a4e8dc
/usr/share/package-licenses/pypi-home_assistant_frontend/625da4e81245c248bff6dbf65a92e3e98d14b7d1
/usr/share/package-licenses/pypi-home_assistant_frontend/669c818f065d6cfbc672b3b9e1943759c7531db2
/usr/share/package-licenses/pypi-home_assistant_frontend/68c9a4a0ed7a38283512b48691ae8e138a0eef2d
/usr/share/package-licenses/pypi-home_assistant_frontend/6bda7eb2ddfd8a99d7e8da50fb6f1e96805f3edd
/usr/share/package-licenses/pypi-home_assistant_frontend/71968af288c4c7d4ed0c4565381830db24dc4dff
/usr/share/package-licenses/pypi-home_assistant_frontend/738d95c9247bf21af162a126da83b312ee64883f
/usr/share/package-licenses/pypi-home_assistant_frontend/7589786cde21e316a987007e9d41d72bc6636a6f
/usr/share/package-licenses/pypi-home_assistant_frontend/7f822fe9341af8f82ad1b0c69aba957822a377cf
/usr/share/package-licenses/pypi-home_assistant_frontend/80a02612c79a42edc043ba543351c469a3980988
/usr/share/package-licenses/pypi-home_assistant_frontend/83389be5ca12156e489018273f6f1e9454eea60c
/usr/share/package-licenses/pypi-home_assistant_frontend/835ee1b049a8047518b8a9c5c4783563e575e23e
/usr/share/package-licenses/pypi-home_assistant_frontend/8eaae83a886ac672f4951ec3845ed8ed6800f330
/usr/share/package-licenses/pypi-home_assistant_frontend/9188b8b3154cc352eab6ef20bce25a641a2d4544
/usr/share/package-licenses/pypi-home_assistant_frontend/971648e1257541060d2781192eadbbd4b25bbd4f
/usr/share/package-licenses/pypi-home_assistant_frontend/9df6942b5a07135e71dea56a6a258ac1159ed21a
/usr/share/package-licenses/pypi-home_assistant_frontend/9fdb1ff9635426575a6738844d37ca296a7df621
/usr/share/package-licenses/pypi-home_assistant_frontend/a00d99a7a63a6f81733e45fef43c5b869114a8e0
/usr/share/package-licenses/pypi-home_assistant_frontend/a8dc9f8fec60a86b68053048c025a56e6b7f8121
/usr/share/package-licenses/pypi-home_assistant_frontend/a8f6fd9479379bced7de01e3dab9de4defda26e0
/usr/share/package-licenses/pypi-home_assistant_frontend/b022ae1a00b41126bc4b72aa14c4b217409cbad2
/usr/share/package-licenses/pypi-home_assistant_frontend/b4f46072474f11d4a34f150fc3d73435b4349e60
/usr/share/package-licenses/pypi-home_assistant_frontend/c52bbed517be898a5cd28c5a45a896ee3bd5d8b1
/usr/share/package-licenses/pypi-home_assistant_frontend/c66394b1e4d56b9ff5804fc9ada793a44874c1d2
/usr/share/package-licenses/pypi-home_assistant_frontend/c780796884df62b955cbb838225a1770ea5937dd
/usr/share/package-licenses/pypi-home_assistant_frontend/c7c71dd8cf0383cb862cf098c82112c6bbfe00c9
/usr/share/package-licenses/pypi-home_assistant_frontend/c9e471b5af473fd9bc91b567c6b400d4ed443fc7
/usr/share/package-licenses/pypi-home_assistant_frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
/usr/share/package-licenses/pypi-home_assistant_frontend/d5e80ede95bb4858eef3759e9fe9b4fbcaf7f351
/usr/share/package-licenses/pypi-home_assistant_frontend/e574e3c0f96a21b6afa716c305ec63c8b35db62a
/usr/share/package-licenses/pypi-home_assistant_frontend/e5a5f9f10965f8ef5f09e477f19ed8e580939e3f
/usr/share/package-licenses/pypi-home_assistant_frontend/e85c7adbabceadcefbb2c4bd6d950e1287e90191
/usr/share/package-licenses/pypi-home_assistant_frontend/eb208c601bcc66bf0a9f23d7fc873698f9799ad4
/usr/share/package-licenses/pypi-home_assistant_frontend/ed241054656f3b1ac94c9156de24b195a052aa31
/usr/share/package-licenses/pypi-home_assistant_frontend/ee8dd7e66e20217fedd62d9529a842bd9200b446
/usr/share/package-licenses/pypi-home_assistant_frontend/f1269f0756bb65173169de89577f83a2373db7a3
/usr/share/package-licenses/pypi-home_assistant_frontend/f12d17e4713167bb7d7334d85cc466402bacff89
/usr/share/package-licenses/pypi-home_assistant_frontend/f357a882b4c98ae48dc95c5ae65016cd63e93365
/usr/share/package-licenses/pypi-home_assistant_frontend/fb3724a403cfac8a891cbd6be583aaa458459643

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
